"""zsh provisioning: the interpreter a session actually prefers to run under.

``session_script.SESSION_SHELL_PREFERENCE`` is ``("zsh", "bash")``, so zsh is the
*preferred* session interpreter wherever it exists, and it is the login shell macOS
ships. bash is a deliberate fallback rather than an equal: the generated session
template carries zsh-specific handling in several places — fd 0 redirection before
a background command's exec wrapper, ``exit`` and trap-local state not surviving a
subshell, ``wait`` interruption semantics — because the two shells genuinely differ
where this project needs them to agree.

The consequence that motivated this module (AI-CLI-s2q2): on a host without zsh,
the 16 real-shell signal regressions in ``test_stale_session_reaper.py`` skip,
which means the shell production prefers is the one nothing verifies. Provisioning
zsh turns that coverage back on, and gives a session the interpreter it was
designed for rather than its fallback.

Two rules shape everything here, both learned the hard way:

1. **Install where the host cannot take it away.** A conda base prefix is a fine
   place to put a tool until that prefix sits on an ephemeral filesystem, at which
   point every restart silently removes it — the same failure that broke tmux in
   AI-CLI-i2ih. So provisioning targets ``native_deps.native_prefix()``, under the
   user's own data directory, and never the manager's default prefix.
2. **A launch adopts, it does not install.** Picking up an already-provisioned zsh
   is a stat plus a PATH edit. Running a package manager is minutes, and doing that
   mid-launch would put a multi-minute stall in front of every session on a host
   where the install cannot succeed. Installation belongs to ``ai setup``,
   ``ai update`` and ``ai doctor``, which a human ran on purpose.

Nothing here raises. zsh is an enhancement — bash runs the session perfectly well —
so its absence must degrade the experience and never block it.
"""

import shutil
import subprocess
import sys

from . import native_deps
from .native_deps import Candidate, InstallResult, attempt_installs

PACKAGE = "zsh"

# System managers, used only when a caller explicitly opts into escalation. The
# rootless prefix installs are generated by native_deps.prefix_installers and come
# first, so these are the last resort rather than the default.
_SYSTEM_INSTALLERS: dict[str, list[Candidate]] = {
    # No "win32" entry: there is no native Windows zsh. It runs under WSL, MSYS2 or
    # Cygwin, and the session template's bash fallback is the right answer there.
    "darwin": [("brew", ["brew", "install", PACKAGE])],
    "linux": [
        ("apt-get", ["apt-get", "install", "-y", PACKAGE]),
        ("dnf", ["dnf", "install", "-y", PACKAGE]),
        ("pacman", ["pacman", "-S", "--noconfirm", PACKAGE]),
        ("zypper", ["zypper", "--non-interactive", "install", PACKAGE]),
    ],
}

_MANUAL_HINTS: dict[str, tuple[str, ...]] = {
    "win32": (
        "wsl --install                        # then use zsh inside WSL",
        "pacman -S zsh                        # inside MSYS2",
        "(there is no native Windows zsh; the session runs under bash instead)",
    ),
    "darwin": ("brew install zsh",),
    "linux": (
        "sudo apt install zsh                 # Debian/Ubuntu",
        "sudo dnf install zsh                 # Fedora/RHEL",
        "sudo pacman -S zsh                   # Arch",
        "sudo zypper install zsh              # openSUSE",
        "micromamba install -c conda-forge zsh   # any Linux, no root",
    ),
}


def zsh_present() -> bool:
    """True when a zsh executable is on PATH. Presence only — see :func:`zsh_runs`."""
    return shutil.which(PACKAGE) is not None


def zsh_runs(timeout: int = 10) -> bool:
    """True when ``zsh --version`` actually executes.

    Execution, not resolution. A provisioned shell can resolve and then die on a
    missing shared library exactly as tmux did (AI-CLI-d89q), and a session whose
    pane interpreter fails to exec is torn down by tmux with nothing but a bare
    ``[exited]`` to act on — so "is it there" is not the question worth asking.
    """
    if not zsh_present():
        return False
    try:
        proc = subprocess.run([PACKAGE, "--version"], capture_output=True, text=True, timeout=timeout, check=False)
    except (OSError, subprocess.SubprocessError):
        return False
    return proc.returncode == 0


def adopt_provisioned_zsh() -> bool:
    """Make a previously provisioned zsh visible, installing nothing.

    The launch-time entry point: a stat and a PATH edit, no subprocess. Returns
    True only when zsh is usable afterwards, so a caller learns the answer to the
    question it has rather than whether a directory happened to exist.
    """
    native_deps.adopt_prefix_bin()
    return zsh_runs()


def install_zsh(timeout: int = 900, allow_root: bool = False) -> InstallResult:
    """Provision zsh, rootless-into-our-own-prefix first. Never raises.

    The timeout is generous because a conda-family solve on a slow filesystem is
    genuinely slow — which is precisely why no launch path may call this.

    Verification re-probes by EXECUTING zsh, after adopting the prefix onto PATH,
    because a package manager's exit status proves neither that a binary landed nor
    that it can run.
    """
    candidates = native_deps.prefix_installers(PACKAGE)
    if allow_root:
        candidates = candidates + _SYSTEM_INSTALLERS.get(sys.platform, [])

    def _verify() -> bool:
        native_deps.adopt_prefix_bin()
        return zsh_runs()

    return attempt_installs(candidates, verify=_verify, timeout=timeout, allow_root=allow_root)


def remediation(result: InstallResult | None = None) -> str:
    """The notice shown when zsh could not be provisioned.

    States what was lost rather than only that something failed: a session still
    runs, under bash, so this is a degradation and the message should read like one.
    """
    lines = [
        "",
        "=" * 72,
        "ai-cli-utils: could not provision zsh — sessions will run under bash instead.",
    ]
    if result is not None and result.detail:
        lines.append(f"  Why: {result.detail}")
    lines += [
        "",
        "  bash runs the session correctly; zsh is the preferred interpreter, not a",
        "  requirement. What you lose is your own zsh startup files inside the session",
        "  pane, and the shell this project's session template is tuned for.",
        "",
        "  Install zsh with one of:",
    ]
    lines += [f"      {hint}" for hint in _MANUAL_HINTS.get(sys.platform, ("install zsh from your package manager",))]
    lines += [
        "",
        "  Then run `ai doctor` to confirm, or open a new shell so PATH picks it up.",
        "=" * 72,
        "",
    ]
    return "\n".join(lines)


def ensure_zsh(auto_install: bool = True, quiet: bool = False, allow_root: bool = False) -> InstallResult:
    """Make zsh usable if it is not, and report whether it now is.

    Cheapest first, and the order matters because only the last step can be slow:

    1. **Adopt** any zsh already provisioned into our prefix — a stat and a PATH
       edit.
    2. **Does zsh run?** Execution, never mere presence.
    3. **Present but unrunnable: repair the loader path.** Free, installs nothing,
       and it is the same discovery repair that fixed tmux — a conda-provisioned
       shell keeps its libraries inside the prefix, so a moved or partially removed
       prefix is exactly the case it handles.
    4. **Install**, rootless into our own prefix, escalating only if the caller
       explicitly allowed it.

    ``installed=True`` also covers "was already there". ``unusable=True`` means
    positively established as unavailable, which for zsh is never fatal: the caller
    continues under bash.
    """
    native_deps.adopt_prefix_bin()
    if zsh_runs():
        return InstallResult(True, tool="already-present")

    if zsh_present():
        repair = native_deps.repair_loader_path([PACKAGE, "--version"])
        if repair.repaired:
            summary = f"{', '.join(repair.missing)} resolved from {', '.join(repair.added_dirs)} via {repair.variable}"
            if not quiet:
                print(f"ai-cli-utils: repaired zsh — {summary}.", file=sys.stderr)
            return InstallResult(True, tool="loader-path", detail=summary)

    if not auto_install:
        return InstallResult(False, detail="auto-install not attempted", unusable=not zsh_present())

    result = install_zsh(allow_root=allow_root)
    if result.installed:
        if not quiet:
            print(f"ai-cli-utils: provisioned zsh via {result.tool}.", file=sys.stderr)
        return result

    if not quiet:
        print(remediation(result), file=sys.stderr)
    return InstallResult(False, tool=result.tool, detail=result.detail, unusable=True)
